# Generated by Django 3.0.5 on 2020-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='uid',
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
