version: '3.4'

services:
    energy-data-postgres:
        image: postgres:11.1
        container_name: energy-data-postgres
        restart: always
        environment:
            POSTGRES_USER: "energydbuser"
            POSTGRES_PASSWORD: "1234"
            POSTGRES_DB: "energydb"
            POSTGRES_INITDB_ARGS: "--encoding='UTF-8'"
            POSTGRES_SERVER: "host.docker.internal"

        volumes:
            # config file
            - ./postgres/config/postgres.conf:/etc/postgres/postgres.conf:ro
            # postgresql logs
            - energy_data_postgres_logs:/var/log/postgresql/
            # postgres paths
            - ./backups/postgres:/backups
            - energy_data_postgres:/var/lib/postgresql/data
        expose:
            - 5432
        command: "postgres -c 'config_file=/etc/postgres/postgres.conf'"

volumes:
  energy_data_postgres:
  energy_data_postgres_logs:
